os: linux
language: cpp
compiler: clang

dist: bionic
addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - ninja-build
      - llvm-dev
      - libclang-dev
      - clang

install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.17.1/cmake-3.17.1.tar.gz
  - tar -zxvf cmake-3.17.1.tar.gz
  - cd cmake-3.17.1
  - ./bootstrap
  - make
  - sudo make install
  - cmake --version

before_script:
  - mkdir build
  - cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H./ -Bbuild -G Ninja

script:
  - cmake --build build --config Debug --target all
  - ctest -C Debug -T test --output-on-failure
