os: linux
language: cpp
compiler: clang

dist: bionic
addons:
  snaps:
    - cmake
    - ninja-build

before_script:
  - mkdir build
  - cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H./ -Bbuild -G Ninja

script:
  - cmake --build build --config Debug --target all
  - ctest -C Debug -T test --output-on-failure
